#!/bin/bash

# To install:

brew install ghostscript
brew install graphicsmagick
brew install poppler
brew install tesseract


# To use:

chron-prepare AScenarioFile.pdf
chron-confirm roster.csv
chron-finish results.json
